### ISSUE TITLE
Version 1.0.0 on NPM is in fact the old version 0.2.1

### ISSUE THREAD

**Issue by blueimp** [mathiasbynens/quoted-printable#3]
Hi @mathiasbynens ,

seems like something went wrong when running npm publish?
The package on NPM is tagged as version 1.0.0, but only contains the older version 0.2.1.

Kind regards and thanks to your work!
Sebastian

**Comment by mathiasbynens** [comment]
v1.0.0 is actually v1.0.0 but with the wrong version number exposed ಠ_ಠ It’s embarrassing, I know.

I just released v1.0.1 to avoid the confusion. Thanks for the heads-up!

**Comment by blueimp** [comment]
Wow that was quick, thanks!
